### ISSUE TITLE
Info: Making a Server

### ISSUE THREAD

**Issue by KingofMidnight** [Fruitloopins/Quarters#8]
Hello! While I don't have much to say, I wanted to inform you that I'm in the process of creating a server and plan to incorporate your plugin. I thought it would be good to let you know in case you're interested or would like to join. I sincerely hope this doesn't cause any inconvenience for you. Your plugin is a fantastic idea, and I truly appreciate its functionality. I hope it continues to thrive and be widely used. (Just tell me in a comment if u want the IP Address of the server)

**Comment by Colt44Magnum** [comment]
Very cool. Now you know since you are using the quarters plugin I suggest the meow plugin as well.

**Comment by KingofMidnight** [comment]
Meow plugin?

**Comment by Fruitloopins** [comment]
https://github.com/Fruitloopins/Meow

I haven't uploaded it to Modrinth yet

**Comment by KingofMidnight** [comment]
> ok

idk if this was a yes or a no but here is the server ip: kmtowny.apexmc.co , ik its apex server but its a server i'm going to evolve to different things later, and yeah its been a while and so far 'not much' is what you can say the server count is
